version: '3.5'

services:
  test_db:
    container_name: db_test
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    image: postgres:14.3-alpine

